Fix panic when a command fails + more
cosmic-utils/examine pull request #10
Opened 2024-10-06 18:40 UTC by sungsphinx

Apologies for most of this being in one whole commit, I had already done quite a lot of code changes and it would be a pain to split it.

Main changes:
- Make wgpu an optional feature (useful for operating systems like Redox OS)
- Fix panicking when either lspci, lspcu or lsusb fail
- If a command fails, it will try to show the error message on the respective page
- Add usbutils to Flatpak, which should make the lsusb command available
- Add cosmic-icons to Flatpak

Minor-ish changes:
- Make the log/output in the terminal prettier
- Change some code to pass clippy
- Change "Uh oh, something went wrong" to "An error occurred"
- Make the app icon bigger

Fixes #9

2024-10-06 22:27 UTC, edfloreshz requested changes
Just a minor change

2024-10-06 22:27 UTC, edfloreshz commented on page.codeberg.sungsphinx.Examine.json
> +	},
This entry has some formatting issues.

2024-10-07 16:22 UTC, sungsphinx commented on page.codeberg.sungsphinx.Examine.json
> +	},
Should be fixed, unless that's not what you meant :sweat_smile:

2024-10-07 16:50 UTC, edfloreshz approved these changes
LGTM!

2024-10-07 18:02 UTC, sungsphinx commented
Should I switch to the cosmic baseapp before merging @edfloreshz?

2024-10-07 18:14 UTC, edfloreshz commented
I still haven't gotten it to build, so I wouldn't recommend it just yet.

2024-10-07 18:26 UTC, merged