chore: update libcosmic (+ other deps I think)
cosmic-utils/examine pull request #23
Opened 2024-11-26 16:13 UTC by sungsphinx

Might fix #22 (sets minimum window size)

2024-11-26 16:19 UTC, ahoneybun commented
Not sure if this is new or just how the page renders. 

![screenshot-2024-11-26-16-18-52](https://github.com/user-attachments/assets/3ca125d7-546f-4168-958a-bdd011fc99bd)

2024-11-26 16:24 UTC, sungsphinx commented
I think it was like that before or similar, not entirely sure though.

2024-11-26 16:46 UTC, ahoneybun approved these changes
Builds and works as expected.

2024-12-10 11:48 UTC, edfloreshz requested changes
Small changes needed, otherwise it looks good.

2024-12-10 11:48 UTC, edfloreshz commented on src/app.rs
> +// impl ContextPage {}
This can be removed

2024-12-10 11:48 UTC, edfloreshz commented on src/app.rs
> +            .author("COSMIC Utilities")
You should be the author, we could add an organization method to link a project to an organization

2024-12-11 19:41 UTC, merged